apiVersion: v1
kind: Pod
metadata:
  name: ebs-app
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo 'Hello from EBS Volume' >> /data/out.txt; sleep 5; done"]
      volumeMounts:
        - mountPath: "/data"
          name: ebs-volume
  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: ebs-pvc
