controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code

  persistence:
    enabled: true
    storageClass: "ebs-sc"
    accessMode: "ReadWriteOnce"
    size: "10Gi"

  serviceType: LoadBalancer
  servicePort: 8080
